server:
  port: 8080

spring:
  datasource:
    # Postgres는 다른 컨테이너이기 때문에 jdbc url을 이렇게 해줘야함
    url: jdbc:postgresql://postgres:5432/${DB_NAME}
    username: cosmoslog
    password: ${DB_PASSWORD:?DB_PASSWORD is required}
  jpa:
    hibernate:
      ddl-auto: validate